version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/freshcart
      JWT_SECRET: change-me
      CORS_ORIGIN: http://localhost,http://localhost:80,http://localhost:8080,http://localhost:3000
      ALLOW_DEV_SEED: "false"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo_data:


