services:
  - type: web
    name: freshcart-api
    env: node
    rootDir: server
    plan: free
    buildCommand: ""
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: ALLOW_DEV_SEED
        value: "false"

  - type: static
    name: freshcart-web
    rootDir: frontend
    plan: free
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: freshcart-api
          envVarKey: RENDER_EXTERNAL_URL


